In [1]:
import numpy as np

arr=np.array([23,35,38,39,29])
print(arr)
newarr=np.array([29,37,29,46])
print(newarr)

[23 35 38 39 29]
[29 37 29 46]


In [2]:
#creating multidimentional array
arr5=np.array([[27,38,30,37,38],
              [28,39,47,49,20],
              ])

print(arr5)

[[27 38 30 37 38]
 [28 39 47 49 20]]


Use numpy Function like zeroes ,ones,full,eye,random rand

In [3]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Use the zero function

In [4]:
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Use the one function to create the matrix of value filled with one 

In [5]:
one_matrix=np.ones((4,4))
print(one_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Use full function to create the matrix filled with particular value

In [6]:
Full_matrix=np.full((4,8),9)
print(Full_matrix)

[[9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9]]


To create the identity matrix use the eye function

In [7]:
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Use the Random function to ceate the random value matrix

In [8]:
random_matrix=np.random.rand(4,4)
print(random_matrix)

[[0.53896479 0.23000568 0.19367647 0.00282015]
 [0.18588742 0.87527082 0.02337386 0.85037707]
 [0.6543428  0.3190782  0.72796584 0.91059441]
 [0.47400649 0.57081363 0.7939023  0.84466389]]


Array attributes

arr.shape

In [9]:
arr=np.array([[27,38,27,29],
              [29,38,48,10]])
arr.shape

(2, 4)

array.size

In [10]:
arr=np.array([28,39,48,39])
arr.size


4

Data type finding function(arr.dtype)

In [11]:
arr=np.array([[28,39,38,49],
              [26,39,94,76]
              ])
arr.dtype

dtype('int64')

In [12]:
arr=np.array(["pratik","vijay","naik"])
arr.dtype

dtype('<U6')

Array slicing and indexing

In [13]:
arr=np.array([29,38,30,28,39])
print(arr[3])


28


In [14]:
arr=np.array([28,39,48,29,29])
print (arr[1:4])
    

[39 48 29]


Slicing 2D arrays

In [15]:
arr2D=np.array([[28,38,49,47],
                [29,38,30,37],
                [28,37,48,93],
                [29,37,38,39]])
print(arr2D[:2,1:])



[[38 49 47]
 [38 30 37]]


In [16]:
arrnew_2=np.array([[19,239,320,2442],[262546,2347,2348,2932],
                   [234,24,23,324]])

print(arrnew_2[2:,1:])

[[ 24  23 324]]


In [17]:
arr=np.array([28,3,34,35,34,32,23,21,98])
print(arr[0::3]) #here the steing is three

[28 35 23]


In [18]:
arr=np.array([28,129,23,29,19,12,123,1237])
print(arr[1:4:1]) #here the slicing start from index 1 and go to the index 3 and steping 1


[129  23  29]


In [19]:
arr=np.array([29,30,34,34,332,23,323,23,23,2323])
print(arr[-1:-5:-1]) #

[2323   23   23  323]


In [20]:
arr=np.array([29,30,34,34,332,23,323,23,23,2323])
print(arr[-1:-5:-2]) #

[2323   23]


slicing 2D array

Acsessing the first Three rows

In [21]:
arr=np.array([[12,23,12,19,39,20,38,49,37],
              [38,48,29,10,38,49,38,34,38],
              [29,38,47,39,49,30,38,38,28],
              [74,20,38,30,48,39,20,28,38]])

print(arr[0:3])

[[12 23 12 19 39 20 38 49 37]
 [38 48 29 10 38 49 38 34 38]
 [29 38 47 39 49 30 38 38 28]]


Aceesing the first three columns

In [22]:
arr=np.array([[27,38,39,64,38,39,47],
              [19,28,38,29,36,49,17],
              [29,35,48,37,39,37,37]])

print(arr[:,0:3])

[[27 38 39]
 [19 28 38]
 [29 35 48]]


accsessing the particular element

In [23]:
arr=np.array([[29,38,47,53,47,28,27,38],
              [72,38,37,29,27,39,27,38],
              [18,29,38,29,39,29,38,38],
              [28,38,39,38,49,35,48,38]])

print(arr[3,6]) #48

48


accessing the particular set of values from the matrix

In [24]:
arr=np.array([[28,38,39,38,27,29,38],
              [19,28,39,37,39,28,29],
              [28,38,29,38,29,39,28],
              [28,39,28,29,38,38,38]])

print(arr[1:,4:])

[[39 28 29]
 [29 39 28]
 [38 38 38]]


slice with steps


In [25]:
arr=np.array([[27,45,28,26,38],
              [28,39,27,28,33],
              [28,37,48,38,29]])
print(arr[: ,::2])

[[27 28 38]
 [28 27 33]
 [28 48 29]]


Mathematical operations

1 Addition

In [26]:
arr1=np.array([18,29,38,38,48,29,48,38])
arr2=np.array([23,87,65,38,27,38,86,37])
sum=arr1 + arr2
print(sum)


[ 41 116 103  76  75  67 134  75]


2 Subtraction

In [27]:
arr1=np.array([29,28,37])
arr2=np.array([36,46,26])
sub= arr1 - arr2
print(sub)

[ -7 -18  11]


Finding Square of the array elements

In [28]:
arr=np.array([[2,2,2,2,2,2],
              [2,2,2,2,2,2],
              [2,2,2,2,2,2]])
print(arr**2)

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


Taking the square root of the array

In [29]:
arr=np.array([29,38,48,39,28,29,23,3,5])
print(np.sqrt(arr))

[5.38516481 6.164414   6.92820323 6.244998   5.29150262 5.38516481
 4.79583152 1.73205081 2.23606798]


Aggregate Functions

1 Sum

In [30]:
arr=np.array([19,29,38,37,37,38,27])
print(np.sum(arr))


225


2 Mean function

In [31]:
arr=np.array([28,37,47,29,37,84,37])
print(np.mean(arr))

42.714285714285715


3 Maximum Element In the array

In [32]:
arr=np.array([13,28,39,38,37,39,20])
print(np.max(arr))


39


4 Minimum Number in an array

In [33]:
arr=np.array([27,28,39,28,29,17])
print(np.min(arr))


17


5 Product of the all elements in an array

In [34]:
arr=np.array([17,28,37,28,39,36,38])
print(np.prod(arr))


26309791872


#Reshape the matrix 

In [35]:
matrix=np.array([28,39,47,23,48,39])
print(matrix.reshape(2,3))

[[28 39 47]
 [23 48 39]]


Transpose of the matrix 

In [36]:
arr=np.array([[29,38,48,30,36,47],
              [46,38,47,26,38,46],
              [28,37,49,37,20,19],
              [28,37,48,39,38,39]])
print(arr.T)

[[29 46 28 28]
 [38 38 37 37]
 [48 47 49 48]
 [30 26 37 39]
 [36 38 20 38]
 [47 46 19 39]]


#Stacking in the martix


1 Vertical stacking

Example 1

In [37]:
arr1=np.array([28,38,48,29,37,38,47])
arr2=np.array([37,48,27,39,36,37,46])
print(np.vstack((arr1,arr2)))

[[28 38 48 29 37 38 47]
 [37 48 27 39 36 37 46]]


Example 2

In [38]:
arr1=np.array([27,38,47,29,37,48,49])
arr2=np.array([65,47,38,47,29,37,46])
print(np.vstack((arr1,arr2)))

[[27 38 47 29 37 48 49]
 [65 47 38 47 29 37 46]]


2 Horinzontal Stacking

In [39]:
arr1=np.array([28,37,48,29,27,39,27])
arr2=np.array([17,37,28,29,38,47,37])

print(np.hstack((arr1,arr2)))

[28 37 48 29 27 39 27 17 37 28 29 38 47 37]


#Filtering Using condition

In [40]:
arr=np.array([28,5,38,28,35,37,16,3,38])
print(arr[arr<10])

[5 3]


In [41]:
arr=np.array([18,29,3,49,38,19,28])
print(arr[arr>10])

[18 29 49 38 19 28]


#Sorting In the arrays


1 sorting in the 1D array

In [42]:
arr=np.array([18,29,37,29,37,19,28])
print(np.sort(arr))

[18 19 28 29 29 37 37]


2 Sorting in the 2D arrays

In [43]:
arr=np.array([[28,37,48,19,37,49,28],
              [38,47,20,38,29,40,28],
              [28,49,47,39,47,20,48]])

print(np.sort(arr))

[[19 28 28 37 37 48 49]
 [20 28 29 38 38 40 47]
 [20 28 39 47 47 48 49]]


1 Vertical sorting in  the 2D  array

In [44]:
arr=np.array([[28,49,20,49,20,48,19,39],
             [28,38,40,28,39,48,38,37],
             [37,49,48,18,29,37,49,38],
             [28,48,37,29,38,49,28,38]])
print(np.sort(arr,axis=1))


[[19 20 20 28 39 48 49 49]
 [28 28 37 38 38 39 40 48]
 [18 29 37 37 38 48 49 49]
 [28 28 29 37 38 38 48 49]]


In [45]:
arr=np.array([[90,28,38,49,29,27,38,30],
              [39,28,39,48,10,28,38,28],
              [46,45,37,48,28,38,39,47]])
print(np.sort(arr,axis=0))

[[39 28 37 48 10 27 38 28]
 [46 28 38 48 28 28 38 30]
 [90 45 39 49 29 38 39 47]]


Condition filtering by using where() Function

In [46]:
arr=np.array([29,48,49,19,29,38,47])
print(np.where(arr>30))


(array([1, 2, 5, 6]),)


Replaced Elements based on the condition by using where function

In [47]:
arr=np.array([28,100,48,101,596,102,69])
print(np.where(arr<50,"pratik","naik"))

['pratik' 'naik' 'pratik' 'naik' 'naik' 'naik' 'naik']


Multiple conditon use by appling the where function

In [48]:
arr=np.array([29,38,48,29,28,27,39])
result=np.where((arr<10)| (arr>20))
print(arr[result])



[29 38 48 29 28 27 39]


Concatinate function

1 For 1D array

In [56]:
arr1=np.array([28,49,37,48,28,40,38])
arr2=np.array([27,37,48,37,38,26,39])

print(np.concatenate((arr1,arr2)))


[28 49 37 48 28 40 38 27 37 48 37 38 26 39]


2 For 2D array (Horizontal Concatenation)

In [57]:
arr1=np.array([[28,3,49],
               [27,49,38],
               [37,49,27]])

arr2=np.array([[25,38,49],
               [37,49,27],
               [38,47,19]])

print(np.concatenate((arr1,arr2),axis=1))

[[28  3 49 25 38 49]
 [27 49 38 37 49 27]
 [37 49 27 38 47 19]]


2 For 2D array (Vertical Concatenation)

In [58]:
arr1=np.array([[37,48,27],
               [27,39,26],
               [35,38,46]])
arr2=np.array([[27,39,48],
               [37,48,36],
               [46,26,38],
               ])

print(np.concatenate((arr1,arr2),axis=0))


[[37 48 27]
 [27 39 26]
 [35 38 46]
 [27 39 48]
 [37 48 36]
 [46 26 38]]


#Remove an element From an Array from particular Axis

1 Remove row (axis=0)

In [ ]:
arr1=np.array([[28,38,47],
               [36,38,47],
               [28,37,28]])
deleted_array=np.delete(arr1,0,axis=0) #remove the row 
print(deleted_array)

[[36 38 47]
 [28 37 28]]


2 Remove column (axis=1)

In [61]:
arr=np.array([[28,37,49],
              [26,38,49],
              [28,49,19]
              ])

print(np.delete(arr,1,axis=1))

[[28 49]
 [26 49]
 [28 19]]


#Cumsum function (Cumulutive sum Function)


For 1D array

In [63]:
arr=np.array([28,38,19,28])
print(np.cumsum(arr))


[ 28  66  85 113]


For 2D array

Vertical axis=1

In [ ]:
arr=np.array([[27,39,37,19,27],
              [37,48,19,37,18],
              [37,48,19,30,48]]) #Row wise
print(np.cumsum(arr,axis=1))

[[ 27  66 103 122 149]
 [ 37  85 104 141 159]
 [ 37  85 104 134 182]]


Horizontal axis=0

In [ ]:
arr=np.array([[36,38,49,18,19],
              [28,37,49,18,20],
              [38,28,39,40,37]]) #column wise
print(np.cumsum(arr,axis=0))

[[ 36  38  49  18  19]
 [ 64  75  98  36  39]
 [102 103 137  76  76]]


#Dot Product In the Numpy of the array

1 For 1D array


In [68]:
arr1=np.array([27,38,46])
arr2=np.array([28,46,28])
print(np.dot(arr1,arr2))

3792


2 For 2D array(It much imp that the matrix follow the law of matrix Multiplication)

In [76]:
arr1=np.array([[2,3,1],
              [6,4,2],
              ])

arr2=np.array([[2,4],
               [2,3],
               [8,8]])

print(np.dot(arr1,arr2))




[[18 25]
 [36 52]]


#Vectorize Function(vectorize function is allowed to use python custom function In the numpy array)

Example 1

In [ ]:
def cube(x):
    return x*x*x  #here Create the custom function

arr=np.array([1,2,3,4,5])
vectorized_array=np.vectorize(cube) #passing the custom function in the vectorize function
result=vectorized_array(arr)  #passing the arr in the vectorized object
print(result)

[  1   8  27  64 125]


2 Example 

In [83]:
def squareRoot(x):
    return x**0.5

arr=np.array([1,4,9,16,25,36])
vectorized_function=np.vectorize(squareRoot)
final_value=vectorized_function(arr)
print(final_value)

[1. 2. 3. 4. 5. 6.]


Example 3

In [86]:
def average(x,y,z):
    average=x+y+z
    return (average)**2


arr1=np.array([1,2,3])
arr2=np.array([2,9,3])
arr3=np.array([6,3,4])

vectorized_function=np.vectorize(average)
final_value=vectorized_function(arr1,arr2,arr3)
print(final_value)    

[ 81 196 100]
